
# SEO settings
title: "kiwi"
title2: "Type" # default: ""
description: ""
keywords: ""
url: http://blog.kiwitype.com # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: https://github.com/hbakkum/hbakkum.github.io
disqus_shortname: "kiwitype"
twitter_username:
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : ""
  job      : ""
  bio      : ""
  thumb    : /images/author.jpg
  email    : hayden.bakkum@gmail.com
  url      : http://hbakkum.github.io
  github   : http://github.com/hbakkum
  linkedin : https://www.linkedin.com/in/haydenbakkum

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site:

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
